// boilerplates/react/files/pages/_error/+Page.tsx
import { usePageContext } from "vike-react/usePageContext";

export default function Page() {
  const { is404 } = usePageContext();
  if (is404) {
    return (
      <>
        <h1>404 Page Not Found</h1>
        <p>This page could not be found.</p>
      </>
    );
  }
  return (
    <>
      <h1>500 Internal Server Error</h1>
      <p>Something went wrong.</p>
    </>
  );
}

// boilerplates/vue/files/pages/_error/+Page.vue
<template>
  <h1>{{ heading }}</h1>
  <p>{{ abortReason }}</p>
</template>

<script lang="ts" setup>
import { usePageContext } from "vike-vue/usePageContext";

const ctx = usePageContext();
let { is404, abortReason } = ctx;
if (!abortReason) {
  abortReason = is404 ? "This page could not be found." : "Something went wrong.";
}
const heading = is404 ? "404 Page Not Found" : "500 Internal Server Error";
</script>
