// boilerplates/solid/files/components/Link.tsx
import { createMemo } from "solid-js";
import { usePageContext } from "vike-solid/usePageContext";

export function Link(props: { href: string; children: string }) {
  const pageContext = usePageContext();
  const isActive = createMemo(() =>
    props.href === "/" ? pageContext.urlPathname === props.href : pageContext.urlPathname.startsWith(props.href)
  );
  return (
    <a href={props.href} class={isActive() ? "is-active" : undefined}>
      {props.children}
    </a>
  );
}

// boilerplates/mantine/files/components/Link.tsx
import { usePageContext } from "vike-react/usePageContext";
import { NavLink } from "@mantine/core";

export function Link({ href, label }: { href: string; label: string }) {
  const pageContext = usePageContext();
  const { urlPathname } = pageContext;
  const isActive = href === "/" ? urlPathname === href : urlPathname.startsWith(href);
  return <NavLink href={href} label={label} active={isActive} />;
}
