// website/pages/_error/+Page.tsx
import { usePageContext } from "vike-solid/usePageContext";

export default function Page() {
  const { is404 } = usePageContext();
  if (is404) {
    return (
      <>
        <h1>Page Not Found</h1>
        <p>This page could not be found.</p>
      </>
    );
  } else {
    return (
      <>
        <h1>Internal Error</h1>
        <p>Something went wrong.</p>
      </>
    );
  }
}

// boilerplates/solid/files/pages/_error/+Page.tsx
import { Show } from "solid-js";
import { usePageContext } from "vike-solid/usePageContext";

export default function Page() {
  const { is404 } = usePageContext();
  return (
    <Show
      when={is404}
      fallback={
        <>
          <h1>Internal Error</h1>
          <p>Something went wrong.</p>
        </>
      }
    >
      <h1>Page Not Found</h1>
      <p>This page could not be found.</p>
    </Show>
  );
}
