// packages/boilerplates/react/files/pages/_error/+Page.tsx
export default Page;

import React from "react";

function Page({ is404, errorInfo }: { is404: boolean; errorInfo?: string }) {
  if (is404) {
    return (
      <>
        <h1>404 Page Not Found</h1>
        <p>This page could not be found.</p>
        <p>{errorInfo}</p>
      </>
    );
  } else {
    return (
      <>
        <h1>500 Internal Server Error</h1>
        <p>Something went wrong.</p>
      </>
    );
  }
}

// boilerplates/solid/files/pages/_error/+Page.tsx
import { Show } from "solid-js";

export default function Page(props: { is404: boolean; errorInfo?: string }) {
  return (
    <Show
      when={props.is404}
      fallback={
        <>
          <h1>500 Internal Server Error</h1>
          <p>Something went wrong.</p>
        </>
      }
    >
      <h1>404 Page Not Found</h1>
      <p>This page could not be found.</p>
      <p>{props.errorInfo}</p>
    </Show>
  );
}
