// boilerplates/react/files/pages/sentry/+Page.tsx
import React from "react";
import * as Sentry from "@sentry/react";

export default function Page() {
  return (
    <>
      <h1>Sentry Browser React</h1>
      {!Sentry.getClient() && (
        <div style={{ color: "red" }}>
          Sentry Client is not initialized! Vite Mode: {import.meta.env.PROD ? "PROD" : "DEV"}
        </div>
      )}

      <ul>
        <li>
          <button
            onClick={() => {
              throw new Error(
                `This is a SENTRY Browser React Test! [${import.meta.env.DEV ? "DEV Mode" : "PROD Mode"}]`,
              );
            }}
          >
            Throw Javascript Error
          </button>
        </li>
      </ul>
    </>
  );
}

// boilerplates/vue-sentry/files/pages/sentry/+Page.vue
<template>
  <div>
    <h1>Sentry Test Page</h1>
    <div v-if="!isSentryClientInitialized" style="color: red">
      Sentry Client is not initialized! Vite Mode: {{ isProdMode ? "PROD" : "DEV" }}
    </div>

    <div>
      <button @click="throwError">Throw Javascript Error</button>
    </div>
  </div>
</template>

<script>
import * as Sentry from "@sentry/vue";
export default {
  data() {
    return {
      isSentryClientInitialized: false,
      isProdMode: import.meta.env.PROD,
    };
  },
  mounted() {
    this.isSentryClientInitialized = !!Sentry.getClient();
  },
  methods: {
    throwError() {
      const mode = import.meta.env.DEV ? "DEV Mode" : "PROD Mode";
      throw new Error(`This is a Vue SENTRY Browser Vue Test! [${mode}]`);
    },
  },
};
</script>
