// packages/boilerplates/react/files/pages/index/+Page.tsx
import React from "react";
import { Counter } from "./Counter";

export default function Page() {
  return (
    <>
      <h1
        //# import.meta.BATI_MODULES?.includes("uikit:tailwindcss")
        className="font-bold text-3xl pb-4"
      >
        My Vike app
      </h1>
      This page is:
      <ul>
        <li>Rendered to HTML.</li>
        <li>
          Interactive. <Counter />
        </li>
      </ul>
    </>
  );
}

// boilerplates/vue/files/pages/index/+Page.vue
<template>
  <!--  import.meta.BATI_MODULES?.includes("tailwindcss") -->
  <h1 class="font-bold text-3xl pb-4">
    My Vike app
  </h1>
  <!--  !import.meta.BATI_MODULES?.includes("tailwindcss") -->
  <h1>
    My Vike app
  </h1>
  This page is:
  <ul>
    <li>Rendered to HTML.</li>
    <li>
      Interactive. <Counter />
    </li>
  </ul>
</template>

<script lang="ts">
import Counter from "../../components/Counter.vue";

const components = { Counter }
export default { components }
</script>
