// packages/boilerplates/solid/files/pages/star-wars/index/+Page.tsx
import { For } from "solid-js";
import type { Movie } from "../types";

export default function Page(props: { movies: Movie[] }) {
  return (
    <>
      <h1>Star Wars Movies</h1>
      <ol>
        <For each={props.movies}>
          {(movie) => (
            <li>
              <a href={`/star-wars/${movie.id}`}>{movie.title}</a> ({movie.release_date})
            </li>
          )}
        </For>
      </ol>
      <p>
        Source: <a href="https://star-wars.brillout.com">star-wars.brillout.com</a>.
      </p>
    </>
  );
}

// packages/boilerplates/react/files/pages/star-wars/index/+Page.tsx
export default Page;

import React from "react";
import type { Movie } from "../types";

function Page({ movies }: { movies: Movie[] }) {
  return (
    <>
      <h1>Star Wars Movies</h1>
      <ol>
        {movies.map(({ id, title, release_date }) => (
          <li key={id}>
            <a href={`/star-wars/${id}`}>{title}</a> ({release_date})
          </li>
        ))}
      </ol>
      <p>
        Source: <a href="https://star-wars.brillout.com">star-wars.brillout.com</a>.
      </p>
    </>
  );
}
