// boilerplates/react/files/pages/star-wars/index/+Page.tsx
import React from "react";
import { useData } from "vike-react/useData";
import type { Data } from "./+data";

export default function Page() {
  const movies = useData<Data>();
  return (
    <>
      <h1>Star Wars Movies</h1>
      <ol>
        {movies.map(({ id, title, release_date }) => (
          <li key={id}>
            <a href={`/star-wars/${id}`}>{title}</a> ({release_date})
          </li>
        ))}
      </ol>
      <p>
        Source: <a href="https://brillout.github.io/star-wars">brillout.github.io/star-wars</a>.
      </p>
    </>
  );
}

// boilerplates/solid/files/pages/star-wars/index/+Page.tsx
import { For } from "solid-js";
import { useData } from "vike-solid/useData";
import type { Data } from "./+data.js";

export default function Page() {
  const { movies } = useData<Data>();
  return (
    <>
      <h1>Star Wars Movies</h1>
      <ol>
        <For each={movies}>
          {(movie) => (
            <li>
              <a href={`/star-wars/${movie.id}`}>{movie.title}</a> ({movie.release_date})
            </li>
          )}
        </For>
      </ol>
      <p>
        Source: <a href="https://brillout.github.io/star-wars">brillout.github.io/star-wars</a>.
      </p>
    </>
  );
}
