// boilerplates/react/files/components/Link.tsx
import { usePageContext } from "vike-react/usePageContext";

export function Link({ href, children }: { href: string; children: string }) {
  const pageContext = usePageContext();
  const { urlPathname } = pageContext;
  const isActive = href === "/" ? urlPathname === href : urlPathname.startsWith(href);
  return (
    <a href={href} className={isActive ? "is-active" : undefined}>
      {children}
    </a>
  );
}

// packages/boilerplates/solid/files/components/Link.tsx
import { createMemo } from "solid-js";
import { usePageContext } from "solide/usePageContext";

export function Link(props: { href: string; children: string }) {
  const pageContext = usePageContext();
  const isActive = createMemo(() =>
    props.href === "/" ? pageContext.urlPathname === props.href : pageContext.urlPathname.startsWith(props.href)
  );
  return (
    <a href={props.href} class={isActive() ? "is-active" : undefined}>
      {props.children}
    </a>
  );
}
