// boilerplates/vue/files/pages/star-wars/@id/+Page.vue
<template>
  <h1>{{ movie.title }}</h1>
  Release Date: {{ movie.release_date }}
  <br />
  Director: {{ movie.director }}
  <br />
  Producer: {{ movie.producer }}
</template>

<script lang="ts" setup>
import { useData } from "vike-vue/useData";
import type { Data } from "./+data.js";

const { movie } = useData<Data>();
</script>

// packages/boilerplates/react/files/pages/star-wars/@id/+Page.tsx
import React from "react";
import type { MovieDetails } from "../types";

export default function Page({ movie }: { movie: MovieDetails }) {
  return (
    <>
      <h1>{movie.title}</h1>
      Release Date: {movie.release_date}
      <br />
      Director: {movie.director}
      <br />
      Producer: {movie.producer}
    </>
  );
}
