// boilerplates/react-telefunc/files/pages/todo/+Page.tsx
import React, { useState } from "react";

import { TodoList } from "./TodoList";
import type { TodoItem } from "../../database/todoItems";

export default function Page({ todoItemsInitial }: { todoItemsInitial: TodoItem[] }) {
  return (
    <>
      <h1>To-do List</h1>
      <TodoList todoItemsInitial={todoItemsInitial} />
      <Counter />
    </>
  );
}

function Counter() {
  const [count, setCount] = useState(0);
  return (
    <div>
      This page is interactive:
      <button type="button" onClick={() => setCount((count) => count + 1)}>
        Counter {count}
      </button>
    </div>
  );
}

// packages/boilerplates/solid-telefunc/files/pages/todo/+Page.tsx
import { createSignal } from "solid-js";
import type { TodoItem } from "../../database/todoItems";
import { TodoList } from "./TodoList";

export default function Page(props: { todoItemsInitial: TodoItem[] }) {
  return (
    <>
      <h1>To-do List</h1>
      <TodoList todoItemsInitial={props.todoItemsInitial} />
      <Counter />
    </>
  );
}

function Counter() {
  const [count, setCount] = createSignal(0);
  return (
    <div>
      This page is interactive:
      <button type="button" onClick={() => setCount((count) => count + 1)}>
        Counter {count()}
      </button>
    </div>
  );
}
