// boilerplates/react/files/pages/todo/+Page.tsx
import type { Data } from "@batijs/shared-todo/pages/todo/+data";
import { useData } from "vike-react/useData";
import { TodoList } from "./TodoList.js";

export default function Page() {
  const data = useData<Data>();
  return (
    <>
      <h1>To-do List</h1>
      <TodoList initialTodoItems={data.todo} />
    </>
  );
}

// boilerplates/vue/files/pages/todo/+Page.vue
<template>
  <div>
    <h1>To-do List</h1>
    <TodoList :initial-todo-items="initialTodoItems" />
  </div>
</template>

<script lang="ts" setup>
import type { Data } from "@batijs/shared-todo/pages/todo/+data";
import { useData } from "vike-vue/useData";
import TodoList from "./TodoList.vue";

const initialTodoItems = useData<Data>();
</script>
