// packages/boilerplates/solid/files/layouts/LayoutDefault.tsx
import "./style.css";
//# import.meta.BATI_MODULES?.includes("uikit:tailwindcss")
import "./tailwind.css";
import logoUrl from "../assets/logo.svg";
import { Link } from "../components/Link";
import type { JSX } from "solid-js";

export default function LayoutDefault(props: { children?: JSX.Element }) {
  return (
    <div
      //# import.meta.BATI_MODULES?.includes("uikit:tailwindcss")
      class="flex max-w-5xl m-auto"
      //# !import.meta.BATI_MODULES?.includes("uikit:tailwindcss")
      style={{
        display: "flex",
        "max-width": "900px",
        margin: "auto",
      }}
    >
      <Sidebar>
        <Logo />
        <Link href="/">Welcome</Link>
        {import.meta.BATI_MODULES?.includes("rpc:telefunc") ? <Link href="/todo">Todo</Link> : undefined}
        <Link href="/star-wars">Data Fetching</Link>
      </Sidebar>
      <Content>{props.children}</Content>
    </div>
  );
}

function Sidebar(props: { children: JSX.Element }) {
  return (
    <div
      id="sidebar"
      //# import.meta.BATI_MODULES?.includes("uikit:tailwindcss")
      class="p-5 flex flex-col shrink-0 border-r-2 border-r-gray-200"
      //# !import.meta.BATI_MODULES?.includes("uikit:tailwindcss")
      style={{
        padding: "20px",
        "flex-shrink": 0,
        display: "flex",
        "flex-direction": "column",
        "line-height": "1.8em",
        "border-right": "2px solid #eee",
      }}
    >
      {props.children}
    </div>
  );
}

function Content(props: { children: JSX.Element }) {
  return (
    <div id="page-container">
      <div
        id="page-content"
        //# import.meta.BATI_MODULES?.includes("uikit:tailwindcss")
        class="p-5 pb-12 min-h-screen"
        //# !import.meta.BATI_MODULES?.includes("uikit:tailwindcss")
        style={{
          padding: "20px",
          "padding-bottom": "50px",
          "min-height": "100vh",
        }}
      >
        {props.children}
      </div>
    </div>
  );
}

function Logo() {
  return (
    <div
      //# import.meta.BATI_MODULES?.includes("uikit:tailwindcss")
      class="p-5 mb-2"
      //# !import.meta.BATI_MODULES?.includes("uikit:tailwindcss")
      style={{
        "margin-top": "20px",
        "margin-bottom": "10px",
      }}
    >
      <a href="/">
        <img src={logoUrl} height={64} width={64} />
      </a>
    </div>
  );
}

// packages/boilerplates/vue/files/layouts/LayoutDefault.vue

{{{! /* We are using the SquirrellyJS template syntax */ _}}}

<template>
  <div class="layout">
    <Sidebar>
      <Logo />
      <Link href="/">
        Welcome
      </Link>
{{{ @if (it.import.meta.BATI_MODULES?.includes("rpc:telefunc")) }}}
      <Link href="/todo">
        Todo
      </Link>
{{{ /if }}}
      <Link href="/star-wars">
        Data Fetching
      </Link>
    </Sidebar>
    <Content><slot /></Content>
  </div>
</template>

<script lang="ts" setup>
import Sidebar from "../components/Sidebar.vue";
import Logo from "../components/Logo.vue";
import Link from "../components/Link.vue";
import Content from "../components/Content.vue";
</script>

<style>
{{{ @if (it.import.meta.BATI_MODULES?.includes("uikit:tailwindcss")) }}}
@import "./tailwind.css"; /* see https://stackoverflow.com/questions/55206901/how-to-import-css-files-in-vue-3-child-components */

{{{ /if }}}
body {
  margin: 0;
  font-family: sans-serif;
}
* {
  box-sizing: border-box;
}
a {
  text-decoration: none;
}
</style>

<style scoped>
.layout {
  display: flex;
  max-width: 900px;
  margin: auto;
}
.content {
  padding: 20px;
  padding-bottom: 50px;
  min-height: 100vh;
  flex-grow: 1;
}
.content {
  transition: opacity 0.1s ease-in;
}
.content.page-transition {
  opacity: 0;
}
</style>
