// packages/boilerplates/react/files/pages/index/Counter.tsx
import React, { useState } from "react";

export function Counter() {
  const [count, setCount] = useState(0);

  return (
    <button
      type="button"
      //# import.meta.BATI_MODULES?.includes("tailwindcss")
      className="inline-block border border-black rounded bg-gray-200 px-2 py-1 text-xs font-medium uppercase leading-normal"
      onClick={() => setCount((count) => count + 1)}
    >
      Counter {count}
    </button>
  );
}

// boilerplates/solid/files/pages/index/Counter.tsx
import { createSignal } from "solid-js";

export { Counter };

function Counter() {
  const [count, setCount] = createSignal(0);

  return (
    <button
      type="button"
      //# import.meta.BATI_MODULES?.includes("tailwindcss")
      class="inline-block border border-black rounded bg-gray-200 px-2 py-1 text-xs font-medium uppercase leading-normal"
      onClick={() => setCount((count) => count + 1)}
    >
      Counter {count()}
    </button>
  );
}
